camunda.bpm.admin-user:
  id: naruto
  password: naruto
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:camunda
    username: naruto
    password: naruto
